apiVersion: v2
name: huly
description: Platform Collective platform — self-hosted deployment
type: application
version: 0.1.0
appVersion: "s0.7.426"
home: https://github.com/Platform-Collective/platform
sources:
  - https://github.com/Platform-Collective/platform-selfhost
  - https://github.com/Platform-Collective/platform
keywords:
  - huly
  - project-management
  - collaboration
